# -*- coding: utf-8 -*-
"""Exercícios6Resolvido.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tRdKmicSRvleZWg9leuva1RrKuJzPcO4
"""

import cv2 as cv
from google.colab.patches import cv2_imshow

"""Fazer o algoritmo de escala de cinza alterando pixel a pixel (sem utilizar a função de conversão pronta da biblioteca)."""

#Vermelho = 0.2126
#Verde = 0.7152
#Azul = 0.0722
 
img = cv.imread("lenna.png")

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    cinza = img[i, j, 0] * 0.0722 + img[i, j, 1] * 0.7152 + img[i, j, 2] * 0.2126
    img[i,j] = [cinza, cinza, cinza]

cv2_imshow(img)

img = cv.imread("lenna.png")

cinza = img[:, :, 0] * 0.0722 + img[:, :, 1] * 0.7152 + img[:, :, 2] * 0.2126
img = cinza

cv2_imshow(img)

"""Fazer um algoritmo de limiarização simples em uma imagem de escala de cinza"""

img = cv.imread('lenna.png')
img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

limiar = 128

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    if img[i, j] < limiar:
      img[i, j] = 0
    else:
      img[i, j] = 255

cv2_imshow(img)

img = cv.imread('lenna.png')
img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

limiar = 128

img[img < limiar] = 0
img[img >= limiar] = 255

cv2_imshow(img)