# -*- coding: utf-8 -*-
"""Exercícios6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAt12jXZD_NTsReiNm56Iy7ZjJElDiim
"""

import cv2 as cv
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt 
import numpy as np

"""Fazer um algoritmo que inverta as cores da imagem (faça ela parecer o negativo de uma foto)"""



"""Fazer o algoritmo de escala de cinza alterando pixel a pixel com slicing (sem utilizar a função de conversão pronta da biblioteca)."""

