# -*- coding: utf-8 -*-
"""ListaExercícios2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5DkEY77obwrPXweUuN31Ewjqc795LoU

# Lista de Exercícios 2

1.	Faça um código que leia 5 números, guarde em uma lista e depois informe o maior deles.

---
"""

lista = []

for i in range(5):
  entrada = input("Digite um número: ")
  entrada_int = int(entrada)
  lista.append(entrada_int)

maior = lista[0]

for item in lista:
  if item > maior:
    maior = item

for i in range(1, len(lista)):
  if lista[i] > maior:
    maior = lista[i]

print("O maior número é", maior)

"""2.	Faça um código que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.

  	    Dicas:

          *   Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
          *   Triângulo Equilátero: três lados iguais;
          *   Triângulo Isósceles: quaisquer dois lados iguais;
          *   Triângulo Escaleno: três lados diferentes.

---





"""

lados = [3, 5, 4]

if lados[0] + lados[1] < lados[2] or lados[0] + lados[2] < lados[1] or lados[1] + lados[2] < lados[0]:
  print("Não é um triângulo")
else:
  if lados[0] == lados[1] and lados[1] == lados[2]:
    print("Equilátero")
  elif lados[0] == lados[1] or lados[1] == lados[2] or lados[0] == lados[2]:
    print("Isósceles")
  else:
    print("Escaleno")

"""3.	Faça um código que peça um valor e mostre se ele é primo."""



"""4.	Sendo `H = 1 + 1/2 + 1/3 + 1/4 + ... + 1/N`, Faça um código que calcule o valor de H com N termos."""



"""5.	Faça um código que leia um vetor de 10 caracteres e diga quantas consoantes foram lidas. Imprima as consoantes."""



"""6.	Faça um código que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:

  *   Mostre a quantidade de valores que foram lidos;
  *   Exiba todos os valores na ordem em que foram informados, um ao lado do outro;
  *   Calcule e mostre a soma dos valores;
  *   Calcule e mostre a média dos valores;
  *   Calcule e mostre a quantidade de valores acima da média calculada;
  *   Calcule e mostre a quantidade de valores abaixo de sete;
"""

