# -*- coding: utf-8 -*-
"""ListaExercicios3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTyl27CId3jA0cIaYnfxSZb_QPsiVz7G

Escreva uma função chamada `num_teste` que aceite um número como entrada. Se o número for maior que 10, a função retornará `"Maior que 10."` Se o número for menor que 10, a função retornará `"Menor que 10."` Se o número for igual a 10, a função deve retornar `"Igual a 10."`
"""



"""2.   Escreva uma função `soma_quadrados(lista)` que calcule a soma dos quadrados dos números na lista lista. Por exemplo, `som_quadrados([2, 3, 4])` deve retornar `4 + 9 + 16`, que é `29`."""



"""3.   Escreva uma função que retorna o número de dígitos de um inteiro.

"""



"""4.   Faça uma função que receba uma string de texto e, começando com um dicionário vazio, faça com que ele tenha como chave as letras do alfabeto e como valor a quantidade de vezes que ela aparece no texto. Cada letra somente deve ser adicionada ao dicionário a primeira vez que ela aparece no texto."""



"""5.   Faça uma função que receba o dicionário do problema anterior e adicione as vogais que não apareceram no texto com o valor 0.

"""

