# -*- coding: utf-8 -*-
"""Exercicios8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dupNTTrW0sMn4bojVsGaBUUXe5bnVcwj

Se você inserir um termo de pesquisa como "clima de Itajaí" na pesquisa do Google, você verá, entre outras coisas, um gráfico mostrando a temperatura em diferentes momentos do dia. 

Sua tarefa aqui é recriar esse gráfico, usando uma cidade de sua escolha, encontre a temperatura em diferentes pontos do dia. Use os dados para criar duas listas no seu programa e criar um gráfico com a hora do dia no eixo x e a temperatura correspondente no eixo y.

O gráfico deve informar como a temperatura varia com a hora do dia. Experimente uma segunda cidade e veja como as duas cidades se comparam plotando as duas linhas no mesmo gráfico.
"""

