# -*- coding: utf-8 -*-
"""ListaExercícios2Resolvida.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LZ9nbZ3DR6w4V9_QXwvz14h-IzL_xbf

# Lista de Exercícios 2
"""

sentence = 'This is another test'

def spin_words(sentence):

    lista = sentence.split(' ')

    new = ""

    for i in lista:

      if len(i) < 5:

        new = "".join(i)

      else:

        i = i[::-1]

        new = new.join(i)

    return new

print(spin_words(sentence))

"""1.	Faça um código que leia 5 números e informe o maior deles.

---


"""

valores = []
for i in range(5):
  val = int(input("Digite um valor: "))
  valores.append(val)

maior = valores[0]
for i in range(1, 5):
  if(valores[i] > maior):
    maior = valores[i]
print("O maior valor é ", maior)

valores = [10, 20, 5, 9, 8]
valores.sort()
print(valores)
print("O maior valor é ", valores[4])

valores = [10, 2, 52, 9, 8]
valores_ordenados = sorted(valores)
print(valores)
print(valores_ordenados)
print("O maior valor é ", valores[4])

print("O maior valor é ", max(valores))

"""2.	Faça um código que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.

  	    Dicas:

          *   Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
          *   Triângulo Equilátero: três lados iguais;
          *   Triângulo Isósceles: quaisquer dois lados iguais;
          *   Triângulo Escaleno: três lados diferentes.

---





"""

lados = []
for i in range(3):
  lado = float(input("Informe um lado do triângulo"))
  lados.append(lado)


if lados[0] + lados[1] > lados[2] and lados[1] + lados[2] > lados[0] and lados[0] + lados[2] > lados[1]:
  print("Forma um triângulo")

lados = sorted(lados)

if lados[0] + lados[1] < lados[2]:
  print("Não forma um triângulo")
else:
  if lados[0] == lados[1] and lados[0] == lados[2]: #lados[0] == lados[1] == lados[2]
    print("Equilátero")
  elif lados[0] != lados[1] and lados[0] != lados[2] and lados[1] != lados[2]:
    print("Escaleno")
  else:
    print("Isóceles")

"""3.	Faça um código que peça um valor e mostre se ele é primo."""

numero = int(input("Digite um valor: "))

is_primo = True
for i in range(2, numero):
  if numero % i == 0:
    is_primo = False
    break

if is_primo == True:
  print("É primo")
else:
  print("Não é primo")

for i in range(2, numero):
  if numero % i == 0:
    print("Não é primo")
    break
else:
  print("É primo")

"""4.	Sendo `H = 1 + 1/2 + 1/3 + 1/4 + ... + 1/N`, Faça um código que calcule o valor de H com N termos."""

N = 7
H = 0
for i in range(1, N + 1):
  H = H + 1/i
print(H)

"""5.	Faça um código que leia um vetor de 10 caracteres e diga quantas consoantes foram lidas. Imprima as consoantes."""

consoantes = "bcdfghjklmnpqrstvwxyz"
consoantes = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z']
c_digitadas = []

for i in range(10):
  c = input("Digite um caracter:")
  if c in consoantes:
    c_digitadas.append(c)

print("Foram digitadas", len(c_digitadas), "consoantes")
print("Elas são", c_digitadas)

"""6.	Faça um código que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:

  *   Mostre a quantidade de valores que foram lidos;
  *   Exiba todos os valores na ordem em que foram informados, um ao lado do outro;
  *   Calcule e mostre a soma dos valores;
  *   Calcule e mostre a média dos valores;
  *   Calcule e mostre a quantidade de valores acima da média calculada;
  *   Calcule e mostre a quantidade de valores abaixo de sete;
"""

valores = []

valor = int(input("Digite um valor: "))
while(valor != -1):
  valores.append(valor)
  valor = int(input("Digite um valor: "))

print("Foram lidos", len(valores), "valores")
print("Valores:", valores)
print("Soma:", sum(valores))
print("Media: ", sum(valores) / len(valores))

print("Valores acima da média: ", end="")
for v in valores:
  if v > sum(valores) / len(valores):
    print(v, end=" ")

print()

print("Valores abaixo de 7: ", end="")
for v in valores:
  if v < 7:
    print(v, end=" ")