# -*- coding: utf-8 -*-
"""ListaExercicios1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UAh8-WeA9DOJe6eLT9bkVyDdegDIHWOZ

1.	Faça um código que peça um número e então mostre a mensagem: ***O número informado foi [número]***

---
"""

numero = int(input("Digite um número:"))
print("O número digitado foi", numero)

"""2.	Faça um código que peça dois números e imprima a soma.

---


"""

numero1 = 10
numero2 = 5
soma = numero1 + numero2

"""3.	Faça um código que peça as 4 notas bimestrais e mostre a média.


---



"""



"""4.	Faça um código que peça o raio de um círculo, calcule e mostre sua área.

---


"""



"""5.	Faça um código que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.

---


"""



"""6.	Faça um código que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.

---


"""



"""7.	Faça um código que peça 2 números inteiros e um número real, calcule e mostre:

          a.	O produto do dobro do primeiro com metade do segundo.
          b.	A soma do triplo do primeiro com o terceiro.
          c.	O terceiro elevado ao cubo.

---



"""



"""8.	João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. 

> João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas.

---




"""



"""9.	Faça um código que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
          a.	Salário bruto.
          b.	Quanto pagou ao INSS.
          c.	Quanto pagou ao sindicato.
          d.	O salário líquido.
        	Calcule os descontos e o salário líquido, conforme abaixo:
	        (+) Salário Bruto
	        (-) IR (11%)
	        (-) INSS (8%)
	        (-) Sindicato (5%)
            (=) Salário Liquido

Obs.: Salário Bruto - Descontos = Salário Líquido.

---



"""



"""10.	Faça um código para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total.

---


"""



"""11.	Faça um código para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam 80 reais ou em galões de 3,6 litros, que custam 25 reais.

Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:

      Comprar apenas latas de 18 litros;
      Comprar apenas galões de 3,6 litros;
      Misturar latas e galões, de forma que o preço seja o menor. 
      
Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias

---



"""



"""12.	Faça um código que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos).

---


"""

