# -*- coding: utf-8 -*-
"""ListaExercicios1Resolvida.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bF10IRkFul5aIeDEWxRxpk-aoE3NDELD

1.	Faça um código que peça um número e então mostre a mensagem: ***O número informado foi [número]***

---
"""

numero = int(input("Digite um número:"))
print("O número digitado foi", numero)

"""2.	Faça um código que peça dois números e imprima a soma.

---


"""

n1 = int(input("Digite um número: "))
n2 = input("Digite outro número: ")
soma = n1 + int(n2)
print(soma)

"""3.	Faça um código que peça as 4 notas bimestrais e mostre a média.


---



"""

n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
n3 = float(input("Digite a terceira nota: "))
n4 = float(input("Digite a quarta nota: "))
media = (n1 + n2 + n3 + n4) / 4
print("Média:", media)

"""4.	Faça um código que peça o raio de um círculo, calcule e mostre sua área.

---


"""

raio = float(input("Digite o raio do círculo: "))
area = 3.14 * raio ** 2
print("Area:", area)

"""5.	Faça um código que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.

---


"""

lado = float(input("Digite o lado do quadrado: "))
area = lado ** 2
print("O dobro da área é", area * 2)

"""6.	Faça um código que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.

---


"""

tErrada = float(input("Digite a temperatura em Ferenheit: "))
tCelsius = (tErrada - 32) * (5 / 9)
print(tCelsius, "graus Celsius")

"""7.	Faça um código que peça 2 números inteiros e um número real, calcule e mostre:

          a.	O produto do dobro do primeiro com metade do segundo.
          b.	A soma do triplo do primeiro com o terceiro.
          c.	O terceiro elevado ao cubo.

---



"""

int1   = int(input("Inteiro 1: "))
int2   = int(input("Inteiro 2: "))
float1 = float(input("Real: "))
print((int1 * 2) * (int2 / 2))
print((int1 * 3) + float1)
print(float1 ** 3)

"""8.	João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. 

> João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas.

---




"""

pescado = int(input("Digite quanto o João pescou: "))
excesso = pescado - 50
multa = excesso * 4
print("Excesso:", excesso, "quilos")
print("Multa:", "R$", multa)

"""9.	Faça um código que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
          a.	Salário bruto.
          b.	Quanto pagou ao INSS.
          c.	Quanto pagou ao sindicato.
          d.	O salário líquido.
        	Calcule os descontos e o salário líquido, conforme abaixo:
	        (+) Salário Bruto
	        (-) IR (11%)
	        (-) INSS (8%)
	        (-) Sindicato (5%)
            (=) Salário Liquido

Obs.: Salário Bruto - Descontos = Salário Líquido.

---



"""

valorHora = float(input("Ganho por hora: "))
horasTrabalhadas = int(input("Horas trabalhadas: "))
salarioBruto = valorHora * horasTrabalhadas
inss = salarioBruto * 0.08
ir = salarioBruto * 0.11
sindicato = salarioBruto * 0.05
salarioLiquido = salarioBruto - inss - ir - sindicato
print(salarioBruto, inss, ir, sindicato, salarioLiquido)

"""10.	Faça um código para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total.

---


"""

area = int(input("Area: "))
litros = area / 3
latas = litros // 18 + 1
preco = latas * 80.00
print(latas, preco)

"""11.	Faça um código para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam 80 reais ou em galões de 3,6 litros, que custam 25 reais.

Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:

      Comprar apenas latas de 18 litros;
      Comprar apenas galões de 3,6 litros;
      Misturar latas e galões, de forma que o preço seja o menor. 
      
Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias

---



"""

area = int(input("Area: "))
litros = area / 6
litros = litros * 1.1

latas = (litros // 18) + 1
preco = latas * 80
print("Só latas: ", latas, "por R$", preco)

galoes = litros // 3.6 + 1
preco = galoes * 25
print("Só galoes: ", galoes, "por R$", preco)

latas = litros // 18
galoes = (litros % 18) // 3.6 + 1
preco = latas * 80 + galoes * 25
print("Latas e galoes: ", latas, "e", galoes, "por R$", preco)

"""12.	Faça um código que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos).

---


"""

tamArquivo = float(input("Tamanho: "))
velocidadeI = float(input("Velocidade: "))
tamArquivoMbits = tamArquivo * 8
tempoEmSegundos = (tamArquivoMbits / velocidadeI) 
tempo = tempoEmSegundos / 60
print("Tempo em minutos do download:", tempo)